apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptocurrencies-postgresql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptocurrencies-postgresql
  template:
    metadata:
      labels:
        app: cryptocurrencies-postgresql
    spec:
      containers:
        - name: cryptocurrencies-postgresql
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cryptocurrencies-postgresql-depl
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cryptocurrencies-postgresql-srv
spec:
  selector:
    app: cryptocurrencies-postgresql
  ports:
    - name: database
      protocol: TCP
      port: 5432
      targetPort: 5432
