apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/common/*
      - ./infra/k8s/dev/*
build:
  local:
    push: false
  artifacts:
    - image: alex448800/favorites
      context: favorites
      docker:
        dockerfile: Dockerfile
