apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/common/*
      - ./infra/k8s/prod/*
build:
  googleCloudBuild:
    projectId: supercoder-cryptocurrencies
  artifacts:
    - image: us.gcr.io/supercoder-cryptocurrencies/favorites
      context: favorites
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
