apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
      - ./infra/k8s/common/*
      - ./infra/k8s/prod/*
build:
  googleCloudBuild:
    projectId: supercoder-cryptocurrencies
  artifacts:
    - image: us.gcr.io/supercoder-cryptocurrencies/cryptocurrencies
      context: cryptocurrencies
      docker:
        dockerfile: Dockerfile
