apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
      - ./.github/actions/supercoder-projects/infra/k8s/prod/*
      - ./.github/actions/supercoder-projects/infra/k8s/common/*
build:
  googleCloudBuild:
    projectId: supercoder-dev
  artifacts:
    - image: us.gcr.io/supercoder-dev/favorites
      context: favorites
      docker:
        dockerfile: Dockerfile
