apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favorites
  template:
    metadata:
      labels:
        app: favorites
    spec:
      containers:
        - name: favorites
          image: alex448800/favorites
          env:
            - name: PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: favorites-depl
                  key: PUBLIC_URL
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: favorites-depl
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: favorites-depl
                  key: FIREBASE_PRIVATE_KEY
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: favorites-depl
                  key: FIREBASE_CLIENT_EMAIL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: favorites-depl
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: favorites-srv
spec:
  selector:
    app: favorites
  ports:
    - name: favorites
      protocol: TCP
      port: 5000
      targetPort: 5000
