apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptocurrencies-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptocurrencies
  template:
    metadata:
      labels:
        app: cryptocurrencies
    spec:
      containers:
        - name: cryptocurrencies
          image: us.gcr.io/supercoder-cryptocurrencies/cryptocurrencies
          env:
            - name: PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: cryptocurrencies
                  key: PUBLIC_URL
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: cryptocurrencies
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: cryptocurrencies
                  key: FIREBASE_PRIVATE_KEY
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cryptocurrencies
                  key: FIREBASE_CLIENT_EMAIL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cryptocurrencies
                  key: DATABASE_URL
            - name: COIN_GECKO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cryptocurrencies
                  key: COIN_GECKO_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: cryptocurrencies-srv
spec:
  selector:
    app: cryptocurrencies
  ports:
    - name: cryptocurrencies
      protocol: TCP
      port: 5001
      targetPort: 5000
