name: Deploy Favorites

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment action
        uses: actions/checkout@v2
        with:
          repository: eduardo-valencia/supercoder-projects
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/supercoder-projects
      - name: Deploy
        uses: ./.github/actions/supercoder-projects/deploy
        with:
          gke_project: ${{ secrets.GKE_PROJECT }}
          gke_sa_key: ${{ secrets.GKE_SA_KEY }}
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
